# Define your website routes here
controllers:
    resource:
        path: ../src/UserInterface/Controller/Website/
        namespace: App\UserInterface
    type: attribute

static_home:
    path:       /{_locale}
    controller: App\UserInterface\Controller\Website\HomeController::home
    methods:    GET|HEAD
    locale: '/%default_locale%/'
    format: html
    requirements:
        _locale: en|fr
        _format: html|xml
